package com.example.mylotteryapp.getInfoLoterias.modelos.loteriaNacional

import kotlinx.serialization.Serializable

@Serializable
data class LoteriaNacional(
    val anyo: String,
    val apertura: String,
    val apuestas: String,
    val cdc: String,
    val cierre: String,
    val contenidosRelacionados: ContenidosRelacionados,
    val cuartosPremios: List<String>,
    val dia_semana: String,
    val escrutinio: List<Escrutinio>,
    val estado: String,
    val extraccionesDeCincoCifras: List<String>,
    val extraccionesDeCuatroCifras: List<ExtraccionesDeCuatroCifra>,
    val extraccionesDeDosCifras: List<ExtraccionesDeDosCifra>,
    val extraccionesDeTresCifras: List<ExtraccionesDeTresCifra>,
    val fecha_sorteo: String,
    val fondo_bote: String,
    val game_id: String,
    val id_sorteo: String,
    val lugar: String,
    val managedBySync: String,
    val modelDraw: Int,
    val mostrarConsignacion: Boolean,
    val mostrarVentas: Boolean,
    val nombre: String,
    val num_sorteo: String,
    val precioDecimo: Double,
    val premioEspecial: PremioEspecial,
    val premio_bote: String,
    val premio_especial: Int? = null,
    val premios: String,
    val primerPremio: PrimerPremio,
    val primer_premio: Int,
    val quintosPremios: List<String>,
    val recaudacion: String,
    val reintegros: List<Reintegro>,
    val segundoPremio: SegundoPremio,
    val tercerosPremios: List<String>,
    val tipoSorteo: String,
    val tipoSorteoGeneral: String,
    val urlListadoOficial: String
)